name: Deploy Firebase Hosting on push

on:
  push:
    branches: [ main ]

concurrency:
  group: hosting-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # firebase.json has a hosting predeploy step that builds the frontend.
      # We still run npm ci above so the build has dependencies available.
      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase --version
          firebase deploy --only hosting --project mindscribe-472408
